[build]
  # 构建命令
  command = "npm run build:web && cd netlify/functions && npm install"
  # 发布目录
  publish = "dist"
  # 函数目录
  functions = "netlify/functions"

[build.environment]
  # Node.js版本
  NODE_VERSION = "18"
  # 设置NPM配置
  NPM_FLAGS = "--legacy-peer-deps"

# 重定向规则
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# 头部设置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# 静态资源缓存
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 字体文件缓存
[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 图标文件缓存
[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 